# Loco yaml export: Simple YAML object
# Project: application.properties conversion
# Release: Working copy
# Locale: pt-BR, Brazilian Portuguese
# Exported by: Unregistered user
# Exported at: Wed, 03 Feb 2021 14:29:59 -0300
---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca-api
    username: postgres
    password: "123"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_creation: "true"
flyway:
  baseline-on-migrate: false
  enabled: true
  locations: classpath:/db/migration
...
